spring.application.name=spring-api

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/minerva?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Jdmm123.}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true

# Excel Storage
eprofe.excel.storage-path=${EXCEL_STORAGE_PATH:./storage/excel}
